### ISSUE TITLE
attempting to send to dgram socket causes a stack overflow

### ISSUE THREAD

**Issue by joeshaw** [maxtaco/tamejs#12]
Attempting to iteratively send chunks out over a UDP multicast socket using tamejs is causing me stack overflows.

Here's the code:

```
var dgram = require('dgram');
var fs = require('fs');

var buffer = fs.readFileSync(process.argv[2]);
var offset = 0;
var socket = dgram.createSocket("udp4");

var MCAST_ADDR = "224.0.0.1";
var MCAST_PORT = 6789;
var CHUNK_SIZE = 512;

while (offset < buffer.length) {
    var chunkLen = Math.min(buffer.length - offset, CHUNK_SIZE);

    console.log("writing chunk from " + offset + " to " + (offset + chunkLen));

    await {
        socket.send(buffer, offset, chunkLen,
                     MCAST_PORT, MCAST_ADDR,
                    defer(var err));
    }

    if (err) throw err;

    offset += chunkLen;
}
```

With a sufficiently large file passed in as the argument on the command-line -- I've been using an mp3 -- I get:

```
[...]
writing chunk from 98304 to 98816
writing chunk from 98816 to 99328
writing c
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
RangeError: Maximum call stack size exceeded
```

Is this a bug in tamejs, or am I doing something wrong?

**Comment by joeshaw** [comment]
From digging into the code inside node which implements dgram.send() it appears as though in the case where the address is an IP address (and doesn't require a DNS lookup), the callback is executed synchronously, creating an additional stack frame.

You can get this to happen with plain old node with something like:

```
function sendData(buffer, offset) {
    var chunkLen = Math.min(buffer.length - offset, CHUNK_SIZE);

    socket.send(buffer, offset, chunkLen, MCAST_PORT, MCAST_ADDR, function(err) {
        if (err) throw err;
        offset += chunkLen;
        if (offset < buffer.length) {
            sendData(buffer, offset);
        }
    });
}
```

**Comment by maxtaco** [comment]
Thanks for the bug report.  This is kind of a bug with your code, kind of a bug in tamejs, depending on how you look at it.  But there's not a good solution in tamejs and there is a reasonable solution in your code. 

The problem is that UDP sends to IP addresses obviously don't block, so you'll never return to the base event loop.  This example is kind of like:

``` javascript
for (var i = 0; i < 1000000; ) {
   await { i++; }
}
```

that we mention not attempting on the README.  If you never return to the main event loop (by waiting for a packet, or timer, etc), then you'll hit a stack limit due to tail recursion in the CPS converted code.

You'll wind up OK if you either don't use await/defer for this loop, or if you insert in the loop artificial delay slots:

``` javascript
await setTimeout (defer (), 1);
```

Seems like you might be smashing the network anyways if you're sending out UDP packets as fast as you can?

In C++, we have a way to do setTimeout (defer(), 0), and it works to clear off the recursion stack.  I wonder if the same thing exists in node?  
More in a few....

**Comment by joeshaw** [comment]
Indeed, I wasn't aware that the callback passed to `dgram.send()` could be called synchronously and recursively.  The setTimeout() workaround does work.  And don't worry about the network, that was just example code. :)

Thanks for the quick reply, I closed the tamejs issue and opened one against Node here: https://github.com/joyent/node/issues/1456
